---
  title: "Final UNdata_
author: "Kelsey McCornack"
date: "2022-10-19"
output: html_document
---
  
```{r, setup, inclue = FALSE}
knitr::opts_knit$set(root.dir = 'C:\\Users\\kmcco\\OneDrive\\Desktop\\DA 485\\Data sets\\Clean Data Sets')
```

```{r, warning = FALSE}
# libraries
library(tidyr)
library(plyr)
library(dplyr)
library(caret)
library(ggplot2)
library(GGally)
library(mvnormtest)
library(factoextra)
library(ggbiplot)
library(caTools)
library(randomForest)

```

```{r}
# function to cat nicely
pretty.cat <- function(text){
  cat('\n', text, '\n')
}
```

```{r}
# Read CSVs
abortion.rate <- read.csv('AbortionRatebyCountry_UNdata.csv')
III.1 <- read.csv('III.1_FamilyPlanningNeedsSatisfied_UNdata.csv')
III.3 <- read.csv('III.3_MaternalMortalityRate_UNdata.csv')
III.4.1 <- read.csv('III.4.1_AntenatalCareRate1+Visits_UNdata.csv')
III.4.4 <- read.csv('III.4.4_AntenatalCare4+Visits_UNdata.csv')
III.5 <- read.csv('III.5_BirthsAttendedbySkilledProfessional.csv')
III.6 <- read.csv('III.6_AgeStandardizedTobaccoUse_WHOdata.csv')
III.7 <- read.csv('III.7_ObesityProportion_UNdata.csv')
III.10 <- read.csv('III.10_LifeExpectancyatAge60_UNdata.csv')
III.11 <- read.csv('III.11_MortalityRateCardivascularCancerDiabetesRespiratoryDisease_WHOdata.csv')
QV.4 <- read.csv('QV.4_MinimumLegalMarriageAgeWithoutConsent_UNData.csv')
V.5 <- read.csv('V.5_AdolescentBirthRate_WHOdata.csv')

# UN Region code
UN.Region.Codes <- read.csv('UN Region Codes.csv')
```

```{r}
# load still birth data set and transform
still.birth <- read.csv('StillbirthRate_UNICEF.csv')
colnames(still.birth) <- c('Country.or.Area', seq(2000, 2019))

names <- colnames(still.birth[-1])

still.birth <- still.birth %>%
  pivot_longer(cols=names,
               names_to = 'Year',
               values_to = 'still.birth.rate',
               values_drop_na = FALSE)

still.birth$still.birth.rate <- still.birth$still.birth.rate/100
still.birth$Year <- as.integer(still.birth$Year)



table(still.birth$Year)

```



## Problem child variables -----------------------------------------------------

```{r, eval = FALSE}
# 2010-2017 only
V.4 <- read.csv('V.4_ProportionofWomenAge20-24MarriedBeforeAge15&Age18_WHOdata.csv')

```

## -----------------------------------------------------------------------------
```{r}
# Fix names
merge.col <- c('Country.or.Area', 'Year')
names(III.7)[1] <- 'Country.or.Area'
names(III.10)[1] <- merge.col[1]
names(III.11)[1] <- merge.col[1]
```


```{r}
# Merge everything into one dataframe
master <- as.data.frame(UN.Region.Codes[,c('Country.or.Area', 'Region.Name', 'Sub.region.Name')])

master <- merge(master, still.birth, by = 'Country.or.Area') %>%
  full_join(abortion.rate, by = merge.col) %>%
  full_join(III.1, by = merge.col) %>%
  full_join(III.3, by = merge.col) %>%
  full_join(III.4.1, by = merge.col) %>%
  full_join (III.4.4, by = merge.col) %>%
  full_join(III.5, by = merge.col) %>%
  full_join(III.6, by = merge.col) %>%
  full_join(III.7, by = merge.col) %>%
  full_join(III.10, by = merge.col) %>%
  full_join(III.11, by = merge.col) %>%
  full_join(QV.4, by = merge.col) %>%
  full_join(V.5, by = merge.col)

table(complete.cases(master))

```

```{r}
# Normalize data with caret package
# https://www.pluralsight.com/guides/normalizing-data-r
preprocess <- preProcess(master[,-c(1:4)], method=c('center','scale'))

normalized <- predict(preprocess, master[,-c(1:4)])

normalized <- cbind(master[1:4], normalized)
summary(normalized)
```

```{r}
boxplot(normalized[-c(1:4)])
```

```{r}
# remove values outside  +- 3 standard deviations
num.val <- normalized[-c(1:4)]

num.val[num.val > 3] <- NA

num.val[num.val < -3] <- NA
no.outliers <- cbind(normalized[1:4], num.val)
boxplot(no.outliers[-c(1:4)])
```


```{r}
# bin by country
vars <- names(no.outliers[-c(1:4)])
vars
country.means <- no.outliers
country.means <- country.means %>%
  group_by(Country.or.Area) %>%
  summarise_at(vars, mean, na.rm = TRUE)

```

## Variable significance tests -------------------------------------------------

```{r}
# cor(a, d, use="pairwise.complete.obs")
for(i in 3:ncol(country.means)){
  cor <- cor(country.means[i], country.means$still.birth.rate, use='pairwise.complete.obs')
  pretty.cat(c(names(country.means[i]), round(cor, 4)))
  pretty.cat(c('complete cases:', table(complete.cases(country.means[c(i, 2)]))['TRUE']))
}

```


```{r}
cor.tests <- cor.test(country.means$Abortion.Rate, country.means$still.birth.rate, use = 'pairwise.complete.obs')

cor.tests <- as.data.frame(cor.tests[c(2:4)])


for(i in 4:ncol(country.means)){
  cor <- cor.test(unlist(country.means[i]), country.means$still.birth.rate, use='pairwise.complete.obs')
  cor.tests <- rbind(cor.tests, as.data.frame(cor[c(2:4)]))
}

rownames(cor.tests) <- names(country.means[-c(1:2)])

cor.tests <- cor.tests[order(desc(abs(cor.tests$estimate))),]

round(cor.tests, 3)

```


```{r}
# Keeping only significant variables
sig.var <- c('Country.or.Area', 'Region.Name', 'Sub.region.Name','Year', 'still.birth.rate','III.5', 'III.3', 'III.4.4', 'III.1')

in.col <- which(colnames(no.outliers) %in% sig.var)
sig.var.only <- no.outliers[in.col]

head(sig.var.only)

```

```{r}
# bin by country
vars <- names(sig.var.only[-c(1:4)])
vars

col.means <- sig.var.only %>%
  group_by(Country.or.Area) %>%
  summarise_at(vars, mean, na.rm = TRUE)

complete.by.country2 <- col.means[complete.cases(col.means),]
complete.by.country2

```

```{r, eval = FALSE}
# Bun by region + 5 year increments
binned <- sig.var.only %>%
  mutate(new_bin = cut(Year, breaks = c(1990, 2000, 2010, 2020)))


vars <- names(sig.var.only[-c(1:4)])
vars
binned <- binned %>%
  group_by(Region.Name, new_bin) %>%
  summarise_at(vars, mean, na.rm = TRUE)

complete.by.region <- binned[complete.cases(binned),]
complete.by.region

# no complete cases
```

```{r}
ggpairs(complete.by.country2[-1])
```


## MANOVA ----------------------------------------------------------------------
```{r}
mshapiro.test(t(as.matrix(complete.by.country2[-c(1:4)])))
?mshapiro.test
```
# Hypothesis of Normality is rejected. Can't perform MANOVA test.

## Cluster Analysis ------------------------------------------------------------

```{r}
# distance matrix
dist <- dist(complete.by.country2[-1])
dist

my.hclust <- hclust(dist, method='average')

plot(my.hclust)


member <- cutree(my.hclust, 3)
table(member)

```


```{r}
# k-means clustering
norm.mat <- as.matrix(complete.by.country2[-1])
norm.mat
k.mean <- kmeans(norm.mat, 3)
k.mean

complete.by.country2$cluster   <- k.mean$cluster
```

```{r}
# https://www.datanovia.com/en/blog/k-means-clustering-visualization-in-r-step-by-step-guide/
fviz_cluster(k.mean, data = norm.mat,
             palette = c("#2E9FDF", "#00AFBB", "#E7B800"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme()
             )

```

## PCA -------------------------------------------------------------------------

```{r}
# Dimension reduction using PCA
res.pca <- prcomp(complete.by.country2[-1], center = TRUE, scale = TRUE)
res.pca

# Coordinates of individuals
ind.coord <- as.data.frame(get_pca_ind(res.pca)$coord)
# Add clusters obtained using the K-means algorithm
ind.coord$cluster <- factor(k.mean$cluster)
# Add Species groups from the original data sett
ind.coord$still.birth.rate <- complete.by.country2$still.birth.rate
# Data inspection
head(ind.coord)
```

```{r}
# biplot
# https://stackoverflow.com/questions/24104503/ggbiplot-change-the-axes-value
ggbiplot(res.pca, groups = as.factor(complete.by.country2$cluster), ellipse = TRUE)+
  xlim(-2.5, 2.5) +
  ggtitle('PCA Biplot')
```


```{r}
# linear model for kicks and gigs
model1 <- lm(complete.by.country2$still.birth.rate ~., data = complete.by.country2[-1])
summary(model1)

plot(model1)
```

## Let's see if abortion laws by grounds change anything

```{r}
year.2007 <- subset(master, master$Year == 2007)

abortion.by.grounds <- read.csv('AbortionLawsbyGrounds_UNdata.csv')
table(still.birth$Year)



```

# Random forest
```{r, warning = FALSE}
# sample(1:1000,1)
set.seed(509)
sample <- sample.split(complete.by.country2$Country.or.Area, SplitRatio = .8)

length(sample)
train <- subset(complete.by.country2, sample == TRUE)
test <- subset(complete.by.country2, sample == FALSE)

```

```{r}
# Random forest after feature selection
# sample(1:1000, 1)
seed <- 860

#Model removing inappropriate vars
var.in <- !names(train) %in% c('Country.or.Area', 'cluster')
var.in
train <- train[var.in]


#Model with all variables
set.seed(860)
model2 <- randomForest(train$still.birth.rate ~ ., data=train, ntree = 1000, mtry = 4,importance = TRUE)
model2

?randomForest

summary(model2)

varImpPlot(model2, main = 'Relative Importance')

```

```{r}
# Define the control
trControl <- trainControl(method = "cv",
    number = 10,
    search = "grid")
trControl

# Run the model
rf_default <- train(still.birth.rate~.,
    data = train,
    method = "rf",
    trControl = trControl)
# Print the results
print(rf_default)

summary(rf_default)
```

```{r}
?rsconnect
```



















